version: '3'

services:
  db:
    container_name: thrifday_db
    image: postgres:13.2
    restart: always
    ports:
      - 54320:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: thrifday_db
    volumes:
      - thrifday_db:/var/lib/docker/volumes/thrifday_db/_data
volumes:
  thrifday_db:
    external: true
